# 应用配置，启动加载此配置
# 命名规则：首字母必须大写
#### web配置 ####
AppName = "ai"
Port = 8080
Env = "test"
TimeoutThreshold = 1000   # 超时告警时间，单位:ms

#### 日志配置 ####
LogFile = "./logs/ai.log"

#### 告警配置 ####
BotWarningEnv = "prod/pre"
RobotURL = "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=xxxx"
MentionWhoList = ["156xxxxxxx1"]

#### database配置 ####
Uri = "mongodb://seaxxxxx:71xxxxxEVqir3@10.xx.xx.xx:2xxx7,xx.xx.64.xx:2xxxx,xx.x8.x4.xx:2xxxx/xxxk?authSource=xxxx"
Database = "xxxx"
Table = ""

#### 业务配置 ####


