# 应用配置，启动加载此配置
# 命名规则：首字母必须大写
#### web配置 ####
AppName = "ai"
Port = 8080
Env = "pre"
TimeoutThreshold = 1   # 超时告警时间，单位:ms

#### 日志配置 ####
LogFile = "./logs/ai.log"

#### 告警配置 ####
BotWarningEnv = "prod/pre"
RobotURL = "https://qyapi.weixin.qq.com/xxx-bin/webhook/send?key=xxxx"
MentionWhoList = ["15xxxxxxxx"]

#### database配置 ####

#### 业务配置 ####


